version: '2'

services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    volumes_from:
      - partkeepr

  partkeepr:
    build: partkeepr
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    env_file: .env
    volumes:
      - mysqldata:/var/lib/mysql

  cron:
    build: cron
    env_file: .env
    volumes_from:
      - partkeepr
      - mysql

volumes:
  mysqldata:
